name: nsd
description: A Flutter plugin for network service discovery and registration (aka NSD / DNS-SD / Bonjour / mDNS).
version: 2.3.1
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd
issue_tracker: https://github.com/sebastianhaberey/nsd/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # production
  nsd_android: ^1.2.2
  nsd_ios: ^1.0.3
  nsd_macos: ^1.0.3
  nsd_platform_interface:
    git:
      url: https://github.com/yamaroni/nsd.git
      path: nsd_platform_interface
      ref: develop
  nsd_windows:
    git:
      url: https://github.com/yamaroni/nsd.git
      path: nsd_windows
      ref: develop

#  # development
#  nsd_android:
#    path: ../nsd_android
#  nsd_ios:
#    path: ../nsd_ios
#  nsd_macos:
#    path: ../nsd_macos
#  nsd_windows:
#    path: ../nsd_windows
#  nsd_platform_interface:
#    path: ../nsd_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: nsd_android
      ios:
        default_package: nsd_ios
      macos:
        default_package: nsd_macos
      windows:
        default_package: nsd_windows
